---
name: 'Test'

on:
  pull_request:
    branches: [ "main", "master", "stage", "staging" ]
    paths-ignore:
      - '**/README.md'
      - '.github/**'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Cloning repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag image:$(date +%s)

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Run tests
        run: echo "Tests passed"
